# Basic colors
foreground              #f1dfda
background              #1a110f
selection_foreground    #442a21
selection_background    #e7bdb1

# Cursor colors
cursor                  #ffb59d
cursor_text_color       #55200c

# URL underline color when hovering with mouse
url_color               #d7c68d

# Kitty window border colors
active_border_color     #ffb59d
inactive_border_color   #53433f
bell_border_color       #ffb4ab

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #55200c
active_tab_background   #ffb59d
inactive_tab_foreground #d8c2bb
inactive_tab_background #53433f
tab_bar_background      #1a110f

# Colors for marks
mark1_foreground #55200c
mark1_background #ffb59d
mark2_foreground #442a21
mark2_background #e7bdb1
mark3_foreground #3a3005
mark3_background #d7c68d

# The 16 terminal colors
# black
color0 #1a110f
color8 #53433f

# red
color1 #ffb4ab
color9 #ffb4ab

# green
color2  #ffb59d
color10 #ffb59d

# yellow
color3  #d7c68d
color11 #d7c68d

# blue
color4  #e7bdb1
color12 #e7bdb1

# magenta
color5  #ffdbd0
color13 #ffdbd0

# cyan
color6  #f4e2a7
color14 #f4e2a7

# white
color7  #f1dfda
color15 #f1dfda
