foreground              #e0e2e8
background              #1c2024
selection_foreground    #d5e4f7
selection_background    #3a4857

cursor                  #9bcbfb
cursor_text_color       #003353

url_color               #d3bfe6

active_border_color     #9bcbfb
inactive_border_color   #42474e
bell_border_color       #ffb4ab

wayland_titlebar_color  system
macos_titlebar_color    system

active_tab_foreground   #cee5ff
active_tab_background   #0d4a73
inactive_tab_foreground #c2c7cf
inactive_tab_background #1c2024
tab_bar_background      #101418

mark1_foreground #003353
mark1_background #9bcbfb
mark2_foreground #233240
mark2_background #b9c8da
mark3_foreground #382a49
mark3_background #d3bfe6

color0 #42474e
color8 #8c9198

color1 #ffb4ab
color9 #93000a

color2  #9bcbfb
color10 #cee5ff

color3  #d3bfe6
color11 #eedbff

color4  #b9c8da
color12 #d5e4f7

color5  #0d4a73
color13 #2f628c

color6  #3a4857
color14 #4f4061

color7  #c2c7cf
color15 #e0e2e8
