# Basic colors
foreground              #e2e2e9
background              #111318
selection_foreground    #283041
selection_background    #bec6dc

# Cursor colors
cursor                  #acc7ff
cursor_text_color       #0e2f60

# URL underline color when hovering with mouse
url_color               #ddbcdf

# Kitty window border colors
active_border_color     #acc7ff
inactive_border_color   #44474e
bell_border_color       #ffb4ab

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #0e2f60
active_tab_background   #acc7ff
inactive_tab_foreground #c4c6d0
inactive_tab_background #44474e
tab_bar_background      #111318

# Colors for marks
mark1_foreground #0e2f60
mark1_background #acc7ff
mark2_foreground #283041
mark2_background #bec6dc
mark3_foreground #3f2844
mark3_background #ddbcdf

# The 16 terminal colors
# black
color0 #111318
color8 #44474e

# red
color1 #ffb4ab
color9 #ffb4ab

# green
color2  #acc7ff
color10 #acc7ff

# yellow
color3  #ddbcdf
color11 #ddbcdf

# blue
color4  #bec6dc
color12 #bec6dc

# magenta
color5  #d7e2ff
color13 #d7e2ff

# cyan
color6  #fbd7fc
color14 #fbd7fc

# white
color7  #e2e2e9
color15 #e2e2e9
