# --------------------------------------------------------------------------------------
#
#   ██╗██╗  ██╗   ██╗ █████╗ ███╗   ███╗██╗██████╗  ██████╗ 
#   ██║██║  ╚██╗ ██╔╝██╔══██╗████╗ ████║██║██╔══██╗██╔═══██╗
#   ██║██║   ╚████╔╝ ███████║██╔████╔██║██║██████╔╝██║   ██║
#   ██║██║    ╚██╔╝  ██╔══██║██║╚██╔╝██║██║██╔══██╗██║   ██║
#   ██║███████╗██║   ██║  ██║██║ ╚═╝ ██║██║██║  ██║╚██████╔╝
#   ╚═╝╚══════╝╚═╝   ╚═╝  ╚═╝╚═╝     ╚═╝╚═╝╚═╝  ╚═╝ ╚═════╝ 
#
#   Created by ilyamiro
#   https://github.com/ilyamiro/nixos-configuration
#
# --------------------------------------------------------------------------------------

source = ~/.config/hypr/colors.conf

# ───────── Core Variables ─────────
source = ~/.config/hypr/config/variables.conf

# Source the submap settings dynamically based on active shell
source = ~/.config/hypr/config/submap.conf

# ───────── Modular Configs ─────────
source = ~/.config/hypr/config/monitors.conf
source = ~/.config/hypr/config/env.conf
source = ~/.config/hypr/config/autostart.conf
source = ~/.config/hypr/config/settings.conf
source = ~/.config/hypr/config/rules.conf
source = ~/.config/hypr/config/keybindings.conf
source = ~/.config/hypr/config/text_macros.conf

# ───────── Cursor Settings ─────────
cursor {
    no_warps = true
}
windowrule = match:class ^(Looking-glass-client)$, float on, size 1920 1080, center on

# ───────── Toggle Shell Keybind ─────────
bind = SUPER SHIFT, X, exec, ~/.config/hypr/scripts/toggle_shell.sh

# ───────── Dynamic Shell Configuration ─────────
source = ~/.config/hypr/config/shell.conf
