[pyprland]

plugins = [
  "scratchpads",
  "magnify",
  "fetch_client_menu",
  "expose"
]
#
[scratchpads.term]
animation = "fromTop"
command = "kitty --class kitty-dropterm"
class = "kitty-dropterm"
size = "65% 50%"

