# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  ◈ MODUS SHELL CONFIGURATION
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

# Autostarts
exec-once = bash -c "cd ~/.config/Modus && source .venv/bin/activate && python main.py"

# Layer Rules
layerrule = blur, modus-notifications
layerrule = xray 0, modus-notifications
layerrule = ignorealpha 0, modus-notifications
layerrule = noanim, modus-notifications

layerrule = animation popin, lockscreen

layerrule = blur, modus-launcher
layerrule = xray 0, modus-launcher
layerrule = ignorealpha 0, modus-launcher
layerrule = animation popin, modus-launcher

layerrule = blur, fabric
layerrule = xray 0, fabric
layerrule = ignorealpha 0, fabric

layerrule = blur, modus
layerrule = xray 0, modus
layerrule = ignorealpha 0, modus

layerrule = animation slide right, notification-center

# Keybindings
bind = $mainMod SHIFT, Y, exec, fabric-cli exec modus1 'app.set_css()'
bind = ALT, Tab, exec, fabric-cli exec modus1 'switcher.show_switcher()'
bind = $mainMod, SPACE, exec, fabric-cli exec modus1 'launcher.show_launcher()'
bind = $mainMod, V, exec, fabric-cli exec modus1 "launcher.show_launcher('clip')"
bind = $mainMod, W, exec, fabric-cli exec modus1 "launcher.show_launcher('wall')"
bind = ALT SHIFT, W, exec, fabric-cli exec modus1 "launcher.show_launcher('wall random', external=True)"
bind = $mainMod, Period, exec, fabric-cli exec modus1 "launcher.show_launcher('em')"
bind = $mainMod, ESCAPE, exec, fabric-cli exec modus1 "launcher.show_launcher('power')"
bind = $mainMod SHIFT, M, exec, fabric-cli exec modus1 "launcher.show_launcher('caffeine on', external=True)"
