# Autostarts
exec-once = bash -c "cd ~/.config/Modus && source .venv/bin/activate && python main.py"

# Layer Rules
layerrule {
    name = "modus-notifications"
    match:namespace = ^(modus-notifications)$
    blur = on
    xray = off
    ignore_alpha = 0.0
    no_anim = on
}

layerrule {
    name = "modus-lockscreen"
    match:namespace = ^(lockscreen)$
    animation = popin
}

layerrule {
    name = "modus-launcher"
    match:namespace = ^(modus-launcher)$
    blur = on
    xray = off
    ignore_alpha = 0.0
    animation = popin
}

layerrule {
    name = "modus-fabric"
    match:namespace = ^(fabric)$
    blur = on
    xray = off
    ignore_alpha = 0.0
}

layerrule {
    name = "modus-modus"
    match:namespace = ^(modus)$
    blur = on
    xray = off
    ignore_alpha = 0.0
}

layerrule {
    name = "modus-notification-center"
    match:namespace = ^(notification-center)$
    animation = slide right
}

# Keybindings
bind = $mainMod SHIFT, Y, exec, fabric-cli exec modus1 'app.set_css()'
bind = ALT, Tab, exec, fabric-cli exec modus1 'switcher.show_switcher()'
bind = $mainMod, SPACE, exec, fabric-cli exec modus1 'launcher.show_launcher()'
bind = $mainMod, V, exec, fabric-cli exec modus1 "launcher.show_launcher('clip')"
bind = $mainMod, W, exec, fabric-cli exec modus1 "launcher.show_launcher('wall')"
bind = ALT SHIFT, W, exec, fabric-cli exec modus1 "launcher.show_launcher('wall random', external=True)"
bind = $mainMod, Period, exec, fabric-cli exec modus1 "launcher.show_launcher('em')"
bind = $mainMod, ESCAPE, exec, fabric-cli exec modus1 "launcher.show_launcher('power')"
bind = $mainMod SHIFT, M, exec, fabric-cli exec modus1 "launcher.show_launcher('caffeine on', external=True)"
