# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  ◈ TEXT MACROS (Pasting via type_text.sh script for instant & error-free typing)
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

# Win+Alt+E -> rioisthebestiloverio@gmail.com
bind = $mainMod ALT, E, exec, ~/.config/hypr/scripts/type_text.sh "rioisthebestiloverio@gmail.com"

# Win+Alt+P -> Password?1
bind = $mainMod ALT, P, exec, ~/.config/hypr/scripts/type_text.sh "Password?1"

# Win+Alt+U -> UGFzc3dvcmQ/MQ==
bind = $mainMod ALT, U, exec, ~/.config/hypr/scripts/type_text.sh "UGFzc3dvcmQ/MQ=="

# Win+Alt+N -> N1FFTHhDdQ==
bind = $mainMod ALT, N, exec, ~/.config/hypr/scripts/type_text.sh "N1FFTHhDdQ=="

# Win+Alt+A -> Abdullah
bind = $mainMod ALT, A, exec, ~/.config/hypr/scripts/type_text.sh "Abdullah"

# Win+Alt+Z -> Azmi
bind = $mainMod ALT, Z, exec, ~/.config/hypr/scripts/type_text.sh "Azmi"

# Win+Alt+F -> Ecys
bind = $mainMod ALT, F, exec, ~/.config/hypr/scripts/type_text.sh "Ecys"

# Win+Alt+L -> Thuzad
bind = $mainMod ALT, L, exec, ~/.config/hypr/scripts/type_text.sh "Thuzad"

# Win+Alt+S -> abdullahazmi@uagateway.org
bind = $mainMod ALT, S, exec, ~/.config/hypr/scripts/type_text.sh "abdullahazmi@uagateway.org"

# Win+Alt+B -> Bronx
bind = $mainMod ALT, B, exec, ~/.config/hypr/scripts/type_text.sh "Bronx"

# Win+Alt+C -> New York
bind = $mainMod ALT, C, exec, ~/.config/hypr/scripts/type_text.sh "New York"

# Win+Alt+D -> Current date (output of date command)
bind = $mainMod ALT, D, exec, ~/.config/hypr/scripts/type_text.sh "date" cmd

# Win+Alt+G -> Open gemini.google
bind = $mainMod ALT, G, exec, xdg-open https://gemini.google
