if status is-interactive
# Commands to run in interactive sessions can go here
end
echo 'zoxide init --cmd cd fish | source' >> ~/.config/fish/config.fish

zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
zoxide init --cmd cd fish | source
